name: bot action

on: [push]
  # schedule:
  #   - cron: 0 0 * * *

jobs:
  solve:
    name: ${{ matrix.OS }}_${{ matrix.PY }}
    runs-on: ${{ matrix.VM }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - VM: windows-latest
            OS: win-64
            CPU: x86_64
            PY: py38
            PY_IMPL: py
            PY_VER: 38
          # - VM: linux-latest
          #   OS: 

          
    steps:
    - name: Checkout maxiconda-bot
      uses: actions/checkout@v2

    - name: Checkout maxiconda-envs
      run: git clone https://github.com/Semi-ATE/maxiconda-envs.git

    - name: Windows specific setup
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
      if: contains(matrix.VM, 'windows-latest')

    - name: solve
      env:
        OS: ${{ matrix.OS }}
        CPU: ${{ matrix.CPU }}
        PY: ${{ matrix.PY}}

        DOCKER_IMG: ${{ matrix.DOCKER_IMG }}
        DOCKER_ARCH: ${{ matrix.DOCKER_ARCH }}
      run: |
        if [[ "$OS_NAME" == "Linux" ]]; then
          bash scripts/solve_for_linux.sh;
        fi
        if [[ "$OS_NAME" == "MacOS" ]]; then
          bash scripts/solve_for_macos.sh;
        fi
        if [[ "$OS_NAME" == "Windows" ]]; then
          source /c/Miniconda3/Scripts/activate;
          source scripts/solve_for_windows.sh;
        fi
      shell: bash

    - name: commit and push
      run: echo commit and push $${{ secrets.GITHUB_TOKEN }}
      shell: bash

