name: Bot action

on: [push, pull_request]
  # schedule:
  #   - cron: 0 0 * * *

jobs:
  linux:
    name: ${{ matrix.OS }}
    runs-on: ${{ matrix.VM }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - VM: ubuntu-latest
            OS: linux-64
          
    steps:
    - name: Checkout maxiconda-bot
      uses: actions/checkout@v2

    - name: Checkout maxiconda-envs
      run: |
        ls
        cd ..
        git clone https://github.com/Semi-ATE/maxiconda-envs.git
        ls

    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        activate-environment: maxiconda-bot
        environment-file: environment.yml
        channel-priority: strict

    - name: solve
      shell: bash -l {0}
      env:
        OS: ${{ matrix.OS }}
        CPU: ${{ matrix.CPU }}
        PY: ${{ matrix.PY}}
        DOCKER_IMG: ${{ matrix.DOCKER_IMG }}
        DOCKER_ARCH: ${{ matrix.DOCKER_ARCH }}
      run: |
        python scripts/solve.py

    - name: Commit files
      run: |
        cd ..
        cd maxiconda-envs
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Update packages ${{ matrix.VM }}" -a

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        branch: main
        directory: "../maxiconda-envs"
        repository: Semi-ATE/maxiconda-envs


  mac:
    name: ${{ matrix.OS }}
    runs-on: ${{ matrix.VM }}
    needs: linux
    strategy:
      fail-fast: false
      matrix:
        include:
          - VM: macos-latest
            OS: osx-64

    steps:
    - name: Checkout maxiconda-bot
      uses: actions/checkout@v2

    - name: Checkout maxiconda-envs
      run: |
        ls
        cd ..
        git clone https://github.com/Semi-ATE/maxiconda-envs.git
        ls

    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        activate-environment: maxiconda-bot
        environment-file: environment.yml
        channel-priority: strict

    - name: solve
      shell: bash -l {0}
      env:
        OS: ${{ matrix.OS }}
        CPU: ${{ matrix.CPU }}
        PY: ${{ matrix.PY}}
        DOCKER_IMG: ${{ matrix.DOCKER_IMG }}
        DOCKER_ARCH: ${{ matrix.DOCKER_ARCH }}
      run: |
        python scripts/solve.py

    - name: Commit files
      run: |
        cd ..
        cd maxiconda-envs
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Update packages ${{ matrix.VM }}" -a

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        branch: main
        directory: "../maxiconda-envs"
        repository: Semi-ATE/maxiconda-envs


  win:
    name: ${{ matrix.OS }}
    runs-on: ${{ matrix.VM }}
    needs: mac
    strategy:
      fail-fast: false
      matrix:
        include:
          - VM: windows-latest
            OS: win-64
          
    steps:
    - name: Checkout maxiconda-bot
      uses: actions/checkout@v2

    - name: Checkout maxiconda-envs
      run: |
        ls
        cd ..
        git clone https://github.com/Semi-ATE/maxiconda-envs.git
        ls

    - name: Setup conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        activate-environment: maxiconda-bot
        environment-file: environment.yml
        channel-priority: strict

    - name: solve
      shell: bash -l {0}
      env:
        OS: ${{ matrix.OS }}
        CPU: ${{ matrix.CPU }}
        PY: ${{ matrix.PY}}
        DOCKER_IMG: ${{ matrix.DOCKER_IMG }}
        DOCKER_ARCH: ${{ matrix.DOCKER_ARCH }}
      run: |
        python scripts/solve.py

    - name: Commit files
      run: |
        cd ..
        cd maxiconda-envs
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Update packages ${{ matrix.VM }}" -a

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        branch: main
        directory: "../maxiconda-envs"
        repository: Semi-ATE/maxiconda-envs
